export const analysisConfig = {
  thresholds: {
    standardDailyHours: 7.5,
    highIntensityOvertimeHours: 10,
    anomalyDailyHours: 11,
    highTaskFragmentationCount: 3,
    highProjectSwitchCount: 3,
    anomalyScoreThreshold: 2,
    lowTopicConfidence: 0.9,
    lowSampleDays: 14,
    highMultiProjectRate: 0.34,
    lowFocusScore: 0.58,
    fixHeavyProjectMinHours: 40,
    fixHeavyMaintenanceMultiplier: 1.2,
    fixHeavyReworkRate: 0.25,
    employeeOverloadHoursMultiplier: 1.18,
    employeeIssueAnomalyDays: 2,
    employeeIssueScoreThreshold: 3,
    employeeHighSeverityScore: 5,
    projectWideParticipationCount: 4,
    projectLowAverageHoursPerPerson: 8,
    projectHighTrendSlope: 2.2,
    projectHighTopicDiversity: 4,
    projectIssueScoreThreshold: 2,
    projectHighSeverityScore: 4,
    lowFeedbackScore: 4,
    aiLowDepthScore: 64,
    aiHighCallCount: 18,
  },
  displayLimits: {
    topNDefault: 10,
    overviewTopProjects: 6,
    overviewRiverProjects: 5,
    overviewRiskEmployees: 8,
    overviewDetailRows: 12,
    employeeRank: 8,
    employeeTrendEmployees: 6,
    employeeHeatmapEmployees: 10,
    employeeHeatmapProjects: 10,
    employeeBoxplot: 10,
    projectPrimary: 8,
    projectTierSize: 5,
    projectTailStart: 10,
    projectTailEnd: 18,
    projectScatterBucketSize: 12,
    correlationTopPairs: 5,
    taskKeywordCount: 12,
    topicKeywordPreview: 6,
    agentIssueCards: 6,
    reportIssueHighlights: 5,
    detailFocusProjects: 6,
    detailFocusSeries: 5,
    detailTaskRows: 16,
    llmIssuePreview: 5,
    llmQualityPreview: 5,
    llmTaskPreview: 10,
  },
  ruleToggles: {
    enableReworkKeywordRules: true,
    enableStageDetectionRules: true,
    showMockCharts: true,
  },
} as const;

export type AnalysisConfig = typeof analysisConfig;
